### ISSUE TITLE
informe descargable - cambios

### ISSUE THREAD

**Issue by ocacgt** [ocacgt/dashboard#11]
Hola Óscar, creemos que el link al informe descargable se pierde donde está ahorita (sección de socios y patrocinadores). Queremos pedirte por favor que agregues a una opción más en ese menú, a la par de donde dice "diseño de los estudios", una que diga descargar informe de los estudios.

El texto en este nuevo espacio sería:

> Descargar versiónd de impresión de ambos estudios: [icono de pdf] ocacgt-informeMapeo.pdf 

También por favor cambiar el nombre del archivo para que sea ocacgt-informeMapeo.pdf

**Comment by odeleongt** [comment]
Moví la parte de agregar encabezado y pie de página a otro issue, ya que son dos cambios diferentes.
