### ISSUE TITLE
Informe descargable - Agregar encabezado y pié de página

### ISSUE THREAD

**Issue by odeleongt** [ocacgt/dashboard#13]
¿Es posible agregar en el pdf un encabezado con el logo del ocacgt y un footer con nuestro link www.ocacgt.org? Ahorita se ve un poco plain y en las páginas siguientes es difícil identificar que los datos vienen del ocacgt

**Comment by ocacgt** [comment]
@odeleongt tener este cambio es importante, ya que permite visibilizar el origen de los datos, si no se puede el logo del ocacgt, quizás se pueda agregar solo el texto Observatorio Contra el Acoso Callejero Guatemala, www.ocacgt.org

Gracias.,
