### ISSUE TITLE
Cambiar formularios incrustrados a link.

### ISSUE THREAD

**Issue by ocacgt** [ocacgt/dashboard#14]
Cambiar los dos formularios incrustrados a links de enlace con ``href=_blank``
Links:
http://ocacgt.org/mapeo-de-acoso-callejero/
http://ocacgt.org/mapeo-de-acoso-callejero-en-el-transporte/

**Comment by ocacgt** [comment]
@odeleongt te enviaremos dos imágenes, para que el link quede en cada imagen/ícono

**Comment by ocacgt** [comment]
@odeleongt estos nos nuevos formularios, ¿debemos darle autorización al dashboard para que los pueda acceder no?

**Comment by ocacgt** [comment]
@odeleongt 
Te envié por correo las imágenes y los textos serían:

Denuncia acoso callejero en calles, parques y otros espacios públicos aquí: <dashboard-btn_acosoTransporte.png>

Denuncia acoso callejero en el transporte público aquí:  <dashboard-btn_acosoTransporte.png>

**Comment by odeleongt** [comment]
El dashboard puede acceder ya a los nuevos formularios. Tristemente el token es para todos los formularios, pero al menos hay que autenticarlo en cada computadora que necesite generar el dashboard.
