### ISSUE TITLE
cambio url de formulario acoso callejero

### ISSUE THREAD

**Issue by ocacgt** [ocacgt/dashboard#5]
Hola! por favor cambiar el url o embed del formulario del estudio de acoso callejero:

`<iframe`` src="https://docs.google.com/forms/d/e/1FAIpQLSexOIYKwH_xT3jPECQq2UjkJa4egkUgnhR_cVtk1Z15IayZ0Q/viewform?embedded=true" width="700" height="520" frameborder="0" marginheight="0" marginwidth="0">Cargando…</iframe>`

el url es este: https://goo.gl/forms/u8VQ849nHQ7lS9qG2

**Comment by odeleongt** [comment]
Algo importante va a ser desactivar el formulario anterior para evitar que se recolecten datos en ambos, porque eso podría hacer que perdamos un poco de información.

@ocacgt, es posible hacer que el anterior redirija al nuevo?

**Comment by ocacgt** [comment]
Sí, es importante hacerlo, creo que lo configuraremos para que no reciba más respuestas y no sé si hay alguna forma de que ya no esté público.... lo veré gracias :D
