### ISSUE TITLE
nuevos campos de dirección

### ISSUE THREAD

**Issue by ocacgt** [ocacgt/dashboard#6]
Hola Óscar, como verás hemos cambiado la forma de leer la dirección, la hemos desplegado en tres campos:

- Avenida
- Calle
- Nombre de lugar o referencia

Para leer los datos del excel que se genera, me imagino que tendrás que modificar el código para leer los tres campos en lugar de uno.

**Comment by odeleongt** [comment]
Así es, esto va a cambiar principalmente dos cosas. Además de esos tres campos, los datos de departamento, municipio, y (cuando aplica) zona también se deben de considerar para esto.

- [ ] La forma de leer los datos para obtener una coordenada. Posiblemente esto ayude a identificar mejor las direcciones (dar seguimiento en #7 ).
- [ ] Opcionalmente agregar un marco de resumen (o reemplazar el mapa en el reporte para imprimir) mostrando el mapa de Guatemala, dividido en departamentos, con el total de reportes por departamento, y para el departamento de Guatemala mostrar el conteo por municipios, y para la ciudad de Guatemala mostrar por zonas (dar seguimiento en #8 ).

**Comment by odeleongt** [comment]
Voy a cerrar este issue, para dar seguimiento a los dos asuntos mencionados arriba (#7  y #8 ) en sus issues separados.
